import { AppDatabase } from '../types';

export const INITIAL_EMPTY_DATABASE: AppDatabase = {
  churchConfig: {
    name: '',
    latitude: 30.0444, // Default coords
    longitude: 31.2357,
    radiusMeters: 150,
    dailyPinCode: '2026',
  },
  currentServiceYear: 'السنة الكنسية الجديدة',
  members: [],
  servants: [],
  attendance: [],
  pastoralRecords: [],
  activeServantSession: null,
  nayrouzRollovers: [],
};

export const SAMPLE_CHURCH_DATABASE: AppDatabase = {
  churchConfig: {
    name: 'كنيسة السيدة العذراء مريم والشهيد مارجرجس',
    latitude: 30.0444,
    longitude: 31.2357,
    radiusMeters: 150,
    dailyPinCode: '7412',
  },
  currentServiceYear: '2026 - 2027 (السنة الكنسية)',
  servants: [
    {
      id: 'srv_1',
      code: 'SRV-01',
      name: 'أ/ مينا سمير يوسف',
      phone: '01223456789',
      whatsapp: '01223456789',
      address: '١٥ شارع الكنيسة، شبرا، القاهرة',
      birthDate: '1992-04-12',
      role: 'stage_supervisor',
      roleTitle: 'أمين خدمة مرحلة حضانة',
      categoryId: 'sunday_school',
      stageId: 'ss_kg',
      notes: 'مسؤول المناهج والأنشطة الإبداعية للأطفال',
      active: true,
      createdAt: '2025-01-01',
    },
    {
      id: 'srv_2',
      code: 'SRV-02',
      name: 'ت/ مارينا عاطف فوزي',
      phone: '01019876543',
      whatsapp: '01019876543',
      address: '٢٢ شارع خلوصي، شبرا',
      birthDate: '1996-08-20',
      role: 'servant',
      roleTitle: 'خادمة فصل ثانية حضانة',
      categoryId: 'sunday_school',
      stageId: 'ss_kg',
      notes: 'مسؤولة ترانيم ومسرح العرائس',
      active: true,
      createdAt: '2025-01-05',
    },
    {
      id: 'srv_3',
      code: 'SRV-03',
      name: 'أ/ بيتر عصام كامل',
      phone: '01144556677',
      whatsapp: '01144556677',
      address: '٨ شارع الترعة البولاقية',
      birthDate: '1989-11-15',
      role: 'stage_supervisor',
      roleTitle: 'أمين مدرسة الشمامسة',
      categoryId: 'deacons',
      stageId: 'deacon_kg',
      notes: 'معلم ألحان ومردات الخولاجي المقدس',
      active: true,
      createdAt: '2025-01-01',
    },
    {
      id: 'srv_admin',
      code: 'SRV-ADM',
      name: 'المهندس / فادي موريس نبيل',
      phone: '01200000000',
      whatsapp: '01200000000',
      address: 'مقر مطرانية الكنيسة',
      birthDate: '1985-06-10',
      role: 'general_admin',
      roleTitle: 'أمين عام التربية الكنسية ومسؤول القطاع',
      categoryId: 'sunday_school',
      stageId: 'all',
      notes: 'صلاحيات عامة على جميع المراحل والاجتماعات',
      active: true,
      createdAt: '2024-09-01',
    },
  ],
  members: [
    {
      id: 'mem_1',
      code: 'KG-101',
      name: 'كيرلس مينا سمير',
      phone: '01223456789',
      parentPhone: '01223456789',
      address: 'شبرا، القاهرة، عمارة ٤ ش النيل',
      birthDate: '2021-03-15',
      gender: 'male',
      categoryId: 'sunday_school',
      stageId: 'ss_kg',
      confessionFather: 'أبونا بولا',
      notes: 'موهوب في حفظ الترانيم، ملتزم بمواعيد القداس',
      status: 'active',
      createdAt: '2025-01-10',
    },
    {
      id: 'mem_2',
      code: 'KG-102',
      name: 'يوستينا رفيق مكرم',
      phone: '01065432109',
      parentPhone: '01065432109',
      address: 'شارع روض الفرج، الدور الثالث',
      birthDate: '2021-07-22',
      gender: 'female',
      categoryId: 'sunday_school',
      stageId: 'ss_kg',
      confessionFather: 'أبونا ميخائيل',
      notes: 'تحب الرسم والتلوين، تحتاج تشجيع في الحفظ',
      status: 'active',
      createdAt: '2025-01-12',
    },
    {
      id: 'mem_3',
      code: 'KG-103',
      name: 'مارك يوسف ناصف',
      phone: '01123344556',
      parentPhone: '01123344556',
      address: 'شارع أحمد حلمي، شبرا',
      birthDate: '2020-11-05',
      gender: 'male',
      categoryId: 'sunday_school',
      stageId: 'ss_kg',
      confessionFather: 'أبونا توماس',
      notes: 'غاب مرتين بسبب نزلة برد - يحتاج اتصال افتقاد',
      status: 'needs_care',
      createdAt: '2025-01-15',
    },
    {
      id: 'mem_4',
      code: 'KG-104',
      name: 'مريم هاني وجيه',
      phone: '01287654321',
      parentPhone: '01287654321',
      address: 'شارع شبرا الرئيسي، بجوار الكنيسة',
      birthDate: '2021-09-01',
      gender: 'female',
      categoryId: 'sunday_school',
      stageId: 'ss_kg',
      confessionFather: 'أبونا يوحنا',
      notes: 'نشيطة ومواظبة على التناول كل جمعة',
      status: 'active',
      createdAt: '2025-01-16',
    },
    {
      id: 'mem_5',
      code: 'DK-201',
      name: 'أنطون بيتر عصام',
      phone: '01144556677',
      parentPhone: '01144556677',
      address: 'شارع الترعة البولاقية',
      birthDate: '2020-05-18',
      gender: 'male',
      categoryId: 'deacons',
      stageId: 'deacon_kg',
      confessionFather: 'أبونا موسى',
      notes: 'رسم إبصلتس ومواظب على مردات الشمامسة',
      status: 'active',
      createdAt: '2025-01-10',
    },
  ],
  attendance: [
    {
      id: 'att_1',
      targetId: 'mem_1',
      targetType: 'member',
      stageId: 'ss_kg',
      date: '2026-10-02',
      sessionType: 'درس خدمة',
      status: 'present',
      verifiedInChurch: true,
      verificationMethod: 'gps',
      recordedByServantName: 'مينا سمير',
      notes: 'حضر في الموعد ومعه الإنجيل',
      timestamp: '2026-10-02T09:15:00Z',
    },
    {
      id: 'att_2',
      targetId: 'mem_2',
      targetType: 'member',
      stageId: 'ss_kg',
      date: '2026-10-02',
      sessionType: 'درس خدمة',
      status: 'present',
      verifiedInChurch: true,
      verificationMethod: 'church_pin',
      recordedByServantName: 'مينا سمير',
      notes: '',
      timestamp: '2026-10-02T09:20:00Z',
    },
    {
      id: 'att_3',
      targetId: 'mem_3',
      targetType: 'member',
      stageId: 'ss_kg',
      date: '2026-10-02',
      sessionType: 'درس خدمة',
      status: 'absent',
      verifiedInChurch: false,
      verificationMethod: 'manual',
      recordedByServantName: 'مينا سمير',
      notes: 'لم يحضر - تم تسجيله للافتقاد',
      timestamp: '2026-10-02T09:30:00Z',
    },
    {
      id: 'att_4',
      targetId: 'mem_4',
      targetType: 'member',
      stageId: 'ss_kg',
      date: '2026-10-02',
      sessionType: 'درس خدمة',
      status: 'present',
      verifiedInChurch: true,
      verificationMethod: 'qr_scanner',
      recordedByServantName: 'مينا سمير',
      notes: 'حضور مبكر وتناول',
      timestamp: '2026-10-02T09:05:00Z',
    },
    // Servant attendance
    {
      id: 'att_srv_1',
      targetId: 'srv_1',
      targetType: 'servant',
      stageId: 'ss_kg',
      date: '2026-10-02',
      sessionType: 'درس خدمة',
      status: 'present',
      verifiedInChurch: true,
      verificationMethod: 'gps',
      recordedByServantName: 'النظام',
      notes: 'حضور مبكر لتحضير القاعة',
      timestamp: '2026-10-02T08:30:00Z',
    },
    {
      id: 'att_srv_2',
      targetId: 'srv_2',
      targetType: 'servant',
      stageId: 'ss_kg',
      date: '2026-10-02',
      sessionType: 'درس خدمة',
      status: 'present',
      verifiedInChurch: true,
      verificationMethod: 'church_pin',
      recordedByServantName: 'مينا سمير',
      notes: '',
      timestamp: '2026-10-02T08:45:00Z',
    },
  ],
  pastoralRecords: [
    {
      id: 'past_1',
      memberId: 'mem_3',
      stageId: 'ss_kg',
      date: '2026-10-03',
      servantName: 'مينا سمير',
      type: 'اتصال هاتفي',
      status: 'تم التواصل',
      notes: 'تم الاتصال بوالدة مارك، كان يعاني من نزلة برد وسيحضر الجمعة القادمة بإذن المسيح.',
      createdAt: '2026-10-03T18:00:00Z',
    },
  ],
  activeServantSession: {
    id: 'srv_1',
    name: 'مينا سمير يوسف',
    phone: '01223456789',
    role: 'stage_supervisor',
    assignedCategory: 'sunday_school',
    assignedStageId: 'ss_kg',
    churchName: 'كنيسة العذراء ومارجرجس',
  },
};
